[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm install --prefix backend"]

[phases.build]
cmds = ["cd backend && npx prisma generate && npx tsc"]

[start]
cmd = "cd backend && npx prisma migrate deploy && npm start"